### ISSUE TITLE
How to assert on stderr with ginkgomon?

### ISSUE THREAD

**Issue by benmoss** [tedsuo/ifrit#14]
Given that the Ginkgomon Runner doesn't expose its session, the only way to assert on its streams seems to be with `Buffer()`. But since `gexec.Session`s only expose `s.Out`, how are you supposed to assert on `s.Err`?

I'd be happy to make a PR, but was curious to know if I was just missing something here, or if you had an opinion about what the right abstraction would be.

**Comment by tedsuo** [comment]
Sorry @benmoss, seems like I accidentally disabled notifications. If this is still an issue for you, I would be fine with a pull request that exposed the session.
