### ISSUE TITLE
grpc support

### ISSUE THREAD

**Issue by julian-hj** [tedsuo/ifrit#24]
Seems kind of silly that this code is living in locket:
https://github.com/cloudfoundry/locket/blob/master/grpcserver/server.go

Seems like we should have generic grpc support in ifrit just like we have http support.  Let us know if you agree and we might maybe cook up a PR.

**Comment by tedsuo** [comment]
Sounds great!

Of note: 
- You would have to give up logging with lager. Probably not a big deal.
- The way service registration works in gRPC will make designing a general purpose constructor a little tricky.

I'm all for it though.

**Comment by tedsuo** [comment]
Maybe the best solution is to hand in service and service description:
```golang
func NewGRPCServer(
    listenAddress string, 
    tlsConfig *tls.Config, 
    service interface{}, 
    serviceDesc *grpc.ServiceDesc,
) ifrit.Runner {
    // yadda yadda
    server := grpc.NewServer(grpc.Creds(credentials.NewTLS(tlsConfig)))
    server.RegisterService(serviceDesc, service)
    // yadda yadda
}
```
Used like so:
```
runner := grpcserver.NewGRPCServer(
    cfg.ListenAddress,
    tlsConfig,
    locketService,
    &models._Locket_serviceDesc,
)
```

**Comment by tedsuo** [comment]
Actually it looks like underscores are "lowercase" and so the service description is not available. What jerks. :/

**Comment by julian-hj** [comment]
Hey Ted, I am finally getting back to this.  My current thinking is to pass both the service and the service registrar function as `interface{}`s and then use some runtime golang reflection ugliness to validate that the function has the right signature and to invoke it.

Let me know if this sounds objectionable--otherwise, look out for the PR if I can manage to make it work.
