### ISSUE TITLE
Updating ginkgomon for Ginkgo V2

### ISSUE THREAD

**Issue by onsi** [tedsuo/ifrit#35]
heyo @tedsuo - hope you are well!  Are you still maintaining ifrit these days?  A few CF folks are running into issues trying to upgrade to Ginkgo V2 and using the `ginkgomon` helper that depends on Ginkgo V1.  Would you be up for me submitting a PR that adds a `ginkgomon_v2` package that depends on Ginkgo V2 instead to unblock folks?

I can also upgrade all the things to Ginkgo v2 if you'd like - but can just keep it simple and focused on the new package instead.

Thanks!

**Comment by tedsuo** [comment]
Hey hey!! Great to hear from you. Yes, I'm happy to accept PR's. I agree with your approach to make a separate package.

**Comment by onsi** [comment]
thanks @tedsuo !  will circle back in a few

**Comment by tedsuo** [comment]
@onsi have you tried to use v2? We good on this one?
